### ISSUE TITLE
Dependency missing from ftp site

### ISSUE THREAD

**Issue by brycepg** [Infinidat/relocatable-python3#4]
I got an error message executing `./bin/build`:

```
Downloading ftp://python.infinidat.com/python/sources/openssl-1.0.2f.tar.gz
While:
  Installing openssl.
Error: Error downloading extends for URL ftp://python.infinidat.com/python/sources/openssl-1.0.2f.tar.gz: <urlopen error ftp error: URLError("ftp error: error_perm('550 No such file or directory.',)",)>
```

Looks like this openssl version is missing from the ftp your company's ftp site.

**Comment by amito** [comment]
I have uploaded all the dependencies to the FTP, so this should work now.
Also, please notice we have updated the installation instructions in the README. To install, you should now run:

> pip install zc.buildout
> buildout bootstrap
> ./bin/buildout
> ./bin/build
